name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.5

  dart_code_metrics: ^5.7.0

  dio: ^5.1.1

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2

  flutter_mobx: ^2.0.6+5

  flutter_svg: ^2.0.4

  get_it: ^7.2.0

  intl: ^0.18.0

  mobx: ^2.1.4

  provider: ^6.0.5

  surf_lint_rules: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
