name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3

  dio: ^5.3.2

  drift: ^2.11.1

  equatable: ^2.0.5

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  flutter_svg: ^2.0.7

  geolocator: ^10.0.1

  http_parser: ^4.0.2

  image_picker: ^1.0.4

  intl: ^0.18.1

  mime: ^1.0.4

  path: ^1.8.3

  path_provider: ^2.1.1

  provider: ^6.0.5

  rxdart: ^0.27.7

  shared_preferences: ^2.2.1

  sqlite3_flutter_libs: ^0.5.17

  surf_lint_rules: ^3.0.0

  yandex_mapkit: ^3.3.3

dev_dependencies:
  build_runner: ^2.4.6

  drift_dev: ^2.11.2

  flutter_lints: ^2.0.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
